export const Animations = {
  skyeIdle: require('../assets/animations/skye.json'),
  skyeWork: require('../assets/animations/skye-working.json'),
  skyeStudy: require('../assets/animations/skye-studying.json'),
  skyeBreak: require('../assets/animations/skye-breaking.json'),
  skyeRest: require('../assets/animations/skye-resting.json'),
  lancelotIdle: require('../assets/animations/lancelot.json'),
  lancelotWork: require('../assets/animations/lancelot-working.json'),
  lancelotStudy: require('../assets/animations/lancelot-studying.json'),
  lancelotBreak: require('../assets/animations/lancelot-breaking.json'),
  lancelotRest: require('../assets/animations/lancelot-resting.json'),
  confetti: require('../assets/animations/confetti.json'),
  heartsSm: require('../assets/animations/hearts-small.json'),
  heartsMd: require('../assets/animations/hearts-medium.json'),
  heartsLg: require('../assets/animations/hearts-large.json'),
} as const;